# 프론트엔드 빌드 단계
FROM node:18 AS frontend-builder
WORKDIR /app/frontend

# 먼저 의존성 설정 복사, Docker 캐시 메커니즘 활용
COPY web/package.json web/pnpm-lock.yaml ./

# pnpm 설치 (호환성 문제를 피하기 위해 버전 고정)
RUN npm install -g pnpm@8
# 환경 변수 설정으로 대화형 프롬프트 비활성화
ENV CI=true
# 의존성 설치 (이때 node_modules는 컨테이너 내에서 생성되며 호스트에서 복사되지 않음)
RUN pnpm install

# 나머지 소스 코드 복사 (호스트의 node_modules가 포함되지 않도록 방지)
COPY web .

# 빌드 산출물 생성
RUN pnpm build && chmod -R 755 dist

# 프론트엔드 서비스 단계
FROM nginx:alpine AS frontend
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /app/frontend/dist /usr/share/nginx/html
# 프론트엔드 포트 노출
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

